// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/app/artists.tsx";
import * as $3 from "./routes/app/catalog/[key].tsx";
import * as $4 from "./routes/app/catalog/index.tsx";
import * as $5 from "./routes/app/index.tsx";
import * as $6 from "./routes/app/login.tsx";
import * as $7 from "./routes/app/messages/[pub].tsx";
import * as $8 from "./routes/app/messages/index.tsx";
import * as $9 from "./routes/app/upload.tsx";
import * as $10 from "./routes/artist/[name]/chat.tsx";
import * as $11 from "./routes/artist/[name]/index.tsx";
import * as $12 from "./routes/documents/tattoo-aftercare-instructions.tsx";
import * as $13 from "./routes/index.tsx";
import * as $14 from "./routes/master/index.tsx";
import * as $15 from "./routes/master/login.tsx";
import * as $$0 from "./islands/ArtistChat.tsx";
import * as $$1 from "./islands/ArtistForm.tsx";
import * as $$2 from "./islands/ArtistLinks.tsx";
import * as $$3 from "./islands/Auth.tsx";
import * as $$4 from "./islands/CatalogItemDetails.tsx";
import * as $$5 from "./islands/CatalogManager.tsx";
import * as $$6 from "./islands/Chat.tsx";
import * as $$7 from "./islands/Form.tsx";
import * as $$8 from "./islands/Gallery.tsx";
import * as $$9 from "./islands/MasterAuth.tsx";
import * as $$10 from "./islands/Messages.tsx";
import * as $$11 from "./islands/NavigationBar.tsx";
import * as $$12 from "./islands/OpenSign.tsx";
import * as $$13 from "./islands/Page.tsx";
import * as $$14 from "./islands/TabBar.tsx";
import * as $$15 from "./islands/Tracker.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/app/artists.tsx": $2,
    "./routes/app/catalog/[key].tsx": $3,
    "./routes/app/catalog/index.tsx": $4,
    "./routes/app/index.tsx": $5,
    "./routes/app/login.tsx": $6,
    "./routes/app/messages/[pub].tsx": $7,
    "./routes/app/messages/index.tsx": $8,
    "./routes/app/upload.tsx": $9,
    "./routes/artist/[name]/chat.tsx": $10,
    "./routes/artist/[name]/index.tsx": $11,
    "./routes/documents/tattoo-aftercare-instructions.tsx": $12,
    "./routes/index.tsx": $13,
    "./routes/master/index.tsx": $14,
    "./routes/master/login.tsx": $15,
  },
  islands: {
    "./islands/ArtistChat.tsx": $$0,
    "./islands/ArtistForm.tsx": $$1,
    "./islands/ArtistLinks.tsx": $$2,
    "./islands/Auth.tsx": $$3,
    "./islands/CatalogItemDetails.tsx": $$4,
    "./islands/CatalogManager.tsx": $$5,
    "./islands/Chat.tsx": $$6,
    "./islands/Form.tsx": $$7,
    "./islands/Gallery.tsx": $$8,
    "./islands/MasterAuth.tsx": $$9,
    "./islands/Messages.tsx": $$10,
    "./islands/NavigationBar.tsx": $$11,
    "./islands/OpenSign.tsx": $$12,
    "./islands/Page.tsx": $$13,
    "./islands/TabBar.tsx": $$14,
    "./islands/Tracker.tsx": $$15,
  },
  baseUrl: import.meta.url,
};

export default manifest;
