// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/app/artists.tsx";
import * as $3 from "./routes/app/catalog/[key].tsx";
import * as $4 from "./routes/app/catalog/index.tsx";
import * as $5 from "./routes/app/index.tsx";
import * as $6 from "./routes/app/login.tsx";
import * as $7 from "./routes/app/upload.tsx";
import * as $8 from "./routes/documents/tattoo-aftercare-instructions.tsx";
import * as $9 from "./routes/index.tsx";
import * as $10 from "./routes/master/index.tsx";
import * as $11 from "./routes/master/login.tsx";
import * as $$0 from "./islands/ArtistForm.tsx";
import * as $$1 from "./islands/ArtistLinks.tsx";
import * as $$2 from "./islands/Auth.tsx";
import * as $$3 from "./islands/CatalogItemDetails.tsx";
import * as $$4 from "./islands/CatalogManager.tsx";
import * as $$5 from "./islands/Form.tsx";
import * as $$6 from "./islands/Gallery.tsx";
import * as $$7 from "./islands/MasterAuth.tsx";
import * as $$8 from "./islands/OpenSign.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/app/artists.tsx": $2,
    "./routes/app/catalog/[key].tsx": $3,
    "./routes/app/catalog/index.tsx": $4,
    "./routes/app/index.tsx": $5,
    "./routes/app/login.tsx": $6,
    "./routes/app/upload.tsx": $7,
    "./routes/documents/tattoo-aftercare-instructions.tsx": $8,
    "./routes/index.tsx": $9,
    "./routes/master/index.tsx": $10,
    "./routes/master/login.tsx": $11,
  },
  islands: {
    "./islands/ArtistForm.tsx": $$0,
    "./islands/ArtistLinks.tsx": $$1,
    "./islands/Auth.tsx": $$2,
    "./islands/CatalogItemDetails.tsx": $$3,
    "./islands/CatalogManager.tsx": $$4,
    "./islands/Form.tsx": $$5,
    "./islands/Gallery.tsx": $$6,
    "./islands/MasterAuth.tsx": $$7,
    "./islands/OpenSign.tsx": $$8,
  },
  baseUrl: import.meta.url,
};

export default manifest;
