// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/api/upload.ts";
import * as $3 from "./routes/artist/sabastian.tsx";
import * as $4 from "./routes/book/[artist].tsx";
import * as $5 from "./routes/consent.tsx";
import * as $6 from "./routes/dashboard.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/login.tsx";
import * as $9 from "./routes/message/[artist].tsx";
import * as $$0 from "./islands/Appointments.tsx";
import * as $$1 from "./islands/Auth.tsx";
import * as $$2 from "./islands/Calendar.tsx";
import * as $$3 from "./islands/Chat.tsx";
import * as $$4 from "./islands/Counter.tsx";
import * as $$5 from "./islands/Diagram.tsx";
import * as $$6 from "./islands/Drawing.tsx";
import * as $$7 from "./islands/Form.tsx";
import * as $$8 from "./islands/Submit.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/api/upload.ts": $2,
    "./routes/artist/sabastian.tsx": $3,
    "./routes/book/[artist].tsx": $4,
    "./routes/consent.tsx": $5,
    "./routes/dashboard.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/login.tsx": $8,
    "./routes/message/[artist].tsx": $9,
  },
  islands: {
    "./islands/Appointments.tsx": $$0,
    "./islands/Auth.tsx": $$1,
    "./islands/Calendar.tsx": $$2,
    "./islands/Chat.tsx": $$3,
    "./islands/Counter.tsx": $$4,
    "./islands/Diagram.tsx": $$5,
    "./islands/Drawing.tsx": $$6,
    "./islands/Form.tsx": $$7,
    "./islands/Submit.tsx": $$8,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
